# CMake 最低版本要求
cmake_minimum_required(VERSION 3.5)

# 定义项目
project(MyBRep)

# 查找 Qt5
find_package(Qt5 5.8 REQUIRED COMPONENTS Widgets)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

# ============================================================
# 数学库
# ============================================================

add_subdirectory(MyMath)

# ============================================================
# B-Rep
# ============================================================

add_subdirectory(MyBRep)

# ============================================================
# MyOpenGL
# ============================================================

add_subdirectory(MyOpenGL)

# ============================================================
# MyBRep OpenGL 显示适配层
# ============================================================

add_subdirectory(MyBRepOpenGL)

# ============================================================
# 测试沙盒
# ============================================================

add_subdirectory(SandBox)